version: "3.9"
services:
  db:
    build: ./docker/mysql
    container_name: gs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gimme_scholarship
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3308:3306"
    networks:
      - gs-net

  fetch:
    build:
      context: ./cmd/scraping
      args:
        PYTHON_VERSION: 3.12
    container_name: local_fetch
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    restart: on-failure
    networks:
      - gs-net

networks:
  gs-net:
    name: gs-net
