name: ecr push image

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - "main"
    paths:
      ["cmd/api/Dockerfile", "cmd/migrate/Dockerfile", "cmd/fetch/Dockerfile"]
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push Docker Image to ECR
        env:
          APP_NAMES: "api migrate fetch"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          for APP_NAME in ${{ env.APP_NAMES }}; do
            make docker/${APP_NAME}/build
            docker tag gimme-scholarship-${APP_NAME}:${{ env.IMAGE_TAG }} ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/gimme-scholarship-${APP_NAME}:${{ env.IMAGE_TAG }}
            docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/gimme-scholarship-${APP_NAME}:${{ env.IMAGE_TAG }}
          done
